site_name: Marvin
site_description: 'Marvin: The AI Engineering Framework'
site_copy: Marvin is a lightweight framework for building AI-powered software that's reliable, scalable, and easy to trust.
site_url: https://askmarvin.ai
docs_dir: docs
nav:
  - Getting Started:
    - src/getting_started/what_is_marvin.md
    - src/getting_started/installation.md
    - src/getting_started/quickstart.ipynb
  - Docs:
    - Overview: src/docs/index.md
    - Configuration:
      - src/docs/configuration/settings.md
      - src/docs/configuration/openai.md
    - Utilities:
      - OpenAI API: src/docs/utilities/openai.ipynb
      - Prompt Engineering: 
        - src/docs/prompts/writing.ipynb
        - src/docs/prompts/executing.ipynb
    - AI Components:
      - Overview: src/docs/components/overview.ipynb
      - AI Model: src/docs/components/ai_model.ipynb
      - AI Classifier: src/docs/components/ai_classifier.ipynb
      - AI Function: src/docs/components/ai_function.ipynb
      - AI Application: src/docs/components/ai_application.ipynb
    - Deployment:
      - src/docs/deployment.ipynb
    - Guides:
      - Slackbot: src/guides/slackbot.md
  - API Reference:
    - src/api_reference/index.md
  - Community:
    - src/community.md
    - src/feedback.md
    - Development:
      - src/development_guide.md
  
theme:
  name: material
  custom_dir: docs/overrides
  font: 
    text: Inter
    code: JetBrains Mono
  logo: img/logos/askmarvin_mascot.jpeg
  favicon: img/logos/askmarvin_mascot.jpeg
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.footer
    - content.action.edit
    - content.code.copy
    - content.code.annotate 
    - toc.follow
    # - toc.integrate 
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
  palette:
    # Palette toggle for light mode
    - scheme: default
      accent: blue
      toggle:
        icon: material/weather-sunny 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
plugins:
  - search
  - mkdocs-jupyter:
      highlight_extra_classes: "jupyter-css"
      ignore_h1_titles: True
  - social:
      cards: !ENV [MKDOCS_SOCIAL_CARDS, false]
      cards_font: Inter
      cards_color:
        fill: "#2d6df6"
  - awesome-pages
  - autolinks 
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
              show_source: False
              show_root_heading: True
              show_object_full_path: False
              show_category_heading: False
              show_bases: False
              show_submodules: False
              show_if_no_docstring: False
              show_signature: False
              heading_level: 2
              filters: ["!^_"]

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:materialx.emoji.twemoji
  #     emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - toc:
      permalink: true
      title: On this page
      
repo_url: https://github.com/prefecthq/marvin
edit_uri: edit/main/docs/
extra:
  get_started: src/getting_started/what_is_marvin/
  analytics:
    provider: google
    property: G-2MWKMDJ9CM
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/prefecthq/marvin
    - icon: fontawesome/brands/discord
      link: https://discord.gg/Kgw4HpcuYG
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/askmarvinai
  generator: false
extra_css:
- static/css/termynal.css
- static/css/custom.css
extra_javascript:
- static/js/termynal.js
- static/js/custom.js
